module:
  pmmi: -100
  acquia_connector: 0
  acquia_purge: 0
  acquia_search: 0
  address: 0
  admin_toolbar: 0
  admin_toolbar_tools: 0
  aggregator: 0
  big_pipe: 0
  blazy: 0
  blazy_ui: 0
  block: 0
  block_content: 0
  breakpoint: 0
  captcha: 0
  chosen: 0
  chosen_field: 0
  chosen_lib: 0
  ckeditor: 0
  colorbutton: 0
  config: 0
  config_devel: 0
  config_filter: 0
  config_installer: 0
  config_split: 0
  config_update: 0
  config_update_ui: 0
  content_moderation: 0
  contextual: 0
  country: 0
  csv_serialization: 0
  ctools: 0
  ctools_block: 0
  datetime: 0
  datetime_range: 0
  dblog: 0
  default_content: 0
  devel: 0
  devel_debug_log: 0
  display_field_copy: 0
  double_field: 0
  dropzonejs: 0
  dropzonejs_eb_widget: 0
  ds: 0
  ds_extras: 0
  dynamic_page_cache: 0
  easy_install: 0
  editor: 0
  embed: 0
  entity_browser: 0
  entity_embed: 0
  externalauth: 0
  fast404: 0
  field: 0
  field_group: 0
  field_permissions: 0
  field_ui: 0
  file: 0
  file_browser: 0
  file_entity: 0
  filter: 0
  flag: 0
  hal: 0
  help: 0
  image: 0
  imce: 0
  inline_entity_form: 0
  kint: 0
  layout_discovery: 0
  link: 0
  link_attributes: 0
  linked_field: 0
  maillog: 0
  mailsystem: 0
  memcache: 0
  memory_profiler: 0
  menu_link_content: 0
  menu_per_role: 0
  menu_ui: 0
  metatag: 0
  metatag_mobile: 0
  metatag_page_manager: 0
  metatag_views: 0
  migrate: 0
  migrate_plus: 0
  migrate_source_csv: 0
  migrate_spreadsheet: 0
  migrate_tools: 0
  node: 0
  options: 0
  page_cache: 0
  page_manager: 0
  page_manager_ui: 0
  panelbutton: 0
  panels: 0
  panels_everywhere: 0
  panels_ipe: 0
  password_policy: 0
  password_policy_character_types: 0
  password_policy_characters: 0
  password_policy_consecutive: 0
  password_policy_history: 0
  password_policy_length: 0
  path: 0
  pathauto: 0
  pmmi_address: 0
  pmmi_company_contact: 0
  pmmi_crawler_detect: 0
  pmmi_facebook: 0
  pmmi_fields: 0
  pmmi_forms: 0
  pmmi_import: 0
  pmmi_page_manager_search: 0
  pmmi_psdata: 0
  pmmi_reports: 0
  pmmi_sales_agent: 0
  pmmi_search: 0
  pmmi_sso: 0
  pmmi_taxonomy: 0
  pmmi_training_provider: 0
  pmmi_twitter: 0
  purge: 0
  purge_drush: 0
  purge_processor_cron: 0
  purge_processor_lateruntime: 0
  purge_queuer_coretags: 0
  purge_tokens: 0
  purge_ui: 0
  queue_ui: 0
  quickedit: 0
  recaptcha: 0
  redirect: 0
  redirect_404: 0
  responsive_image: 0
  rest: 0
  schema_article: 0
  schema_event: 0
  schema_image_object: 0
  schema_item_list: 0
  schema_job_posting: 0
  schema_metatag: 0
  schema_organization: 0
  schema_product: 0
  schema_review: 0
  schema_service: 0
  schema_video_object: 0
  schema_web_page: 0
  schema_web_site: 0
  search_api: 0
  search_api_solr: 0
  seckit: 0
  selectize: 0
  serialization: 0
  simple_sitemap: 0
  slick: 0
  slick_ui: 0
  slick_views: 0
  stage_file_proxy: 0
  system: 0
  taxonomy: 0
  tb_megamenu: 0
  telephone: 0
  text: 0
  token: 0
  toolbar: 0
  ultimate_cron: 0
  update: 0
  user: 0
  varnish_purge_tags: 0
  varnish_purger: 0
  video: 0
  view_unpublished: 0
  viewfield: 0
  views: 0
  views_block_filter_block: 0
  views_data_export: 0
  views_field_formatter: 0
  views_field_view: 0
  views_ui: 0
  webform: 0
  webform_ui: 0
  webform_views: 0
  workflows: 0
  yoast_seo: 0
  webform_bootstrap: 1
theme:
  stable: 0
  classy: 0
  seven: 0
  bootstrap: 0
  pmmi_bootstrap: 0
_core:
  default_config_hash: m2GVq11UAOVuNgj8x0t5fMOPujpvQQ_zxLoaly1BMEU
profile: config_installer
