user: demo
pass: demo
print: ''
allow_cli: true
_core:
  default_config_hash: x8SBz0HYCE0Chvb4_trXiGtZ3EWsy-Jcc87XTmCvirM
credential_provider: shield
credentials:
  shield:
    user: demo
    pass: demo
