<?php

/**
 * @file
 * Contains pmmi_twitter.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function pmmi_twitter_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the pmmi_twitter module.
    case 'help.page.pmmi_twitter':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('PMMI Twitter') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function pmmi_twitter_theme() {
  $theme = [];
  $theme['pmmi_twitter_block'] = [
    'render element' => 'elements',
    'file' => 'pmmi_twitter.page.inc',
    'template' => 'pmmi-twitter-block',
  ];
  return $theme;
}
